### ISSUE TITLE
Add a search field

### ISSUE THREAD

**Issue by pwadenz** [ninxsoft/JamfProSwitcher#2]
Thanks for taking the time to create this. I have a growing list of entries and it would be really handy to have a search bar at the top to allow me to filter the list?

**Comment by ninxsoft** [comment]
Thanks for the kind words!

Search sounds like a great idea, I have implemented search + filtering in [another project](https://github.com/ninxsoft/Bombardier), so it shouldn't be too hard to implement :smiley:.

**Comment by ninxsoft** [comment]
Search field has been added in #4, and version [2.1](https://github.com/ninxsoft/JamfProSwitcher/releases/tag/v2.1) has been released!
