### ISSUE TITLE
Last entry does not save

### ISSUE THREAD

**Issue by pwadenz** [ninxsoft/JamfProSwitcher#3]
I notice that when I add a server to the list if I close the app without first pressing "Add Server" it will lose that entry on a relaunch of the app. Would it be possible to have a "Save" button instead or, have it so that it saves the last entry without needing to press "Add Server"?

**Comment by ninxsoft** [comment]
I'm struggling to replicate the behaviour you have mentioned.

Clicking the **Add Server** button should add a row to the bottom of the list, and the following changes will trigger a save to disk:
* Adding a row
* Moving a row up or down (re-ordering)
* Deleting a row
* Closing the app

Are you able to confirm the contents of the preferences file when these types of changes are made?

`~/Library/Containers/com.ninxsoft.jamfproswitcher/Data/Library/Preferences/com.ninxsoft.jamfproswitcher.plist`

**Comment by ninxsoft** [comment]
Can I confirm if this is still an issue?

**Comment by ninxsoft** [comment]
@pwadenz thanks for touching base with me!

It appears the issue occurs when the app is quit via the menubar (⌘ + Q) but not when the window is closed by clicking on the red close button.

Should be simple enough to fix - I need to invoke a save / write to disk when the app is quit, not just when the window is closed.

**Comment by ninxsoft** [comment]
Fixed in dcc67ea205dde83ee66c9b6e018db71928c69432

Version 2.1.1 has been [released](https://github.com/ninxsoft/JamfProSwitcher/releases)!
