### ISSUE TITLE
I like this new version but...

### ISSUE THREAD

**Issue by howieisaacks** [ninxsoft/JamfProSwitcher#7]
Two things. 

First, installing it over an older version of the app obliterates the saved servers. I thought maybe if I moved the plist file from one of my Macs to my other it would transfer all of the servers after I recreated all of them in the new version. It doesn't. It seems that this new version stores its settings in a new location other than ~/Library/Preferences.

Second, I don't see the option to quit Jamf Admin when I switch to another Jamf Pro server. I liked that feature a lot and I would appreciate having it back.

I used to use a shell script to change the Jamf plist file each time I wanted to switch to another Jamf Pro server. I would use the scripts menubar icon do do this. I think that Jamf Pro Switcher is a great app and I appreciate the work put into it.

**Comment by ninxsoft** [comment]
**JamfProSwitcher.app** is a sandboxed application, so the preferences are stored in a container:

`~/Library/Containers/com.ninxsoft.jamfproswitcher/Data/Library/Preferences/com.ninxsoft.jamfproswitcher.plist`

You can read up more about the **App Sandbox Container Directory** here: [App Sandbox in Depth](https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html)

As for the request to bring back the ability to quit apps on close, this is now part of the next build.
